"""Generate docs/action-reference.md from action.yml and the reusable workflow.

The reference is a build product, not a hand-maintained page: chargate's README and its
generated reference had already drifted about a default before anyone noticed. Run with
``--check`` in CI to fail when the committed file no longer matches the source.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
ACTION = ROOT / "action.yml"
OUT = ROOT / "docs" / "reference" / "action.md"


def cell(text: str | None) -> str:
    """Collapse whitespace and escape what would otherwise break the table.

    A `|` inside a cell starts a new column. Descriptions here legitimately contain
    them — ``auto | uv | pip`` is how the choices read — and unescaped they made
    markdownlint report "Too many cells, extra data will be missing", which is exactly
    what rendered: the tail of every such description was dropped from the page.
    """
    collapsed = re.sub(r"\s+", " ", (text or "").strip()).replace("|", r"\|")

    # Everything below is one lesson learned three times: an action description is prose
    # written for `--help`, and dropping it into a markdown table renders it as markup.
    # Each of these silently DELETED content from the published page rather than looking
    # wrong, which is why they are escaped here rather than fixed per description:
    #
    #   `|`        starts a new column, truncating the row
    #   `<repo>`   parses as an HTML tag and vanishes
    #   `* a`      parses as emphasis, eating the asterisks
    #
    # Escaping happens only OUTSIDE code spans: inside backticks these are already
    # literal, and an escape there renders as the escape.
    parts = collapsed.split("`")
    for i in range(0, len(parts), 2):  # even indexes are outside code spans
        chunk = parts[i].replace("<", "&lt;").replace(">", "&gt;")
        chunk = re.sub(r"([*_])", r"\\\1", chunk)
        # A bare URL is valid markdown but escapes the theme's link styling, so give it
        # a code span rather than leaving markdownlint to complain about every one.
        chunk = re.sub(r"(?<!\]\()(?<!`)(https?://[^\s)\]]+)", r"`\1`", chunk)
        parts[i] = chunk
    collapsed = "`".join(parts)

    # An empty cell renders as `|  |`, which markdownlint flags as bad column style and
    # which reads as a missing value rather than a deliberate one.
    return collapsed or "—"


def default(value: object) -> str:
    return f"`{value}`" if value not in ("", None) else "not set"


def render() -> str:
    action = yaml.safe_load(ACTION.read_text(encoding="utf-8"))

    assert not any(  # nosec: B101 — generator script, not bytecode-optimised; guards a doc invariant
        spec.get("required") for spec in action["inputs"].values()
    ), "action.yml has a required input — update the prose in render() to match"

    lines = [
        "# Action reference",
        "",
        "<!-- sources: action.yml -->",
        "",
        "Generated by `scripts/gen_action_reference.py` from `action.yml`. Edit the action, not",
        "this page. For the task-shaped version, see [Using the action](../action.md).",
        "",
        "## Action inputs",
        "",
        f"`MagmaMoose/diatreme@v2` — all {len(action['inputs'])} inputs are optional.",
        "",
        "| Input | Default | Description |",
        "| --- | --- | --- |",
    ]
    for key, spec in action["inputs"].items():
        lines.append(
            f"| `{key}` | {default(spec.get('default'))} | {cell(spec.get('description'))} |"
        )

    lines += ["", "## Action outputs", "", "| Output | Description |", "| --- | --- |"]
    for key, spec in action["outputs"].items():
        lines.append(f"| `{key}` | {cell(spec.get('description'))} |")

    # MD047: a file must end with exactly one newline.
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args(argv)

    generated = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != generated:
            print(f"{OUT.relative_to(ROOT)} is stale. Run: python scripts/gen_action_reference.py")
            return 1
        print("action-reference.md is up to date")
        return 0
    OUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
